"""
Continuous Monitoring System for ESC Market Intelligence
=========================================================

Scheduled job that runs alongside daily data ingestion:
  1. Checks for new IPART publications
  2. Checks for new Ecovantage and NMG market updates
  3. Checks for NSW DCCEEW publications
  4. Runs new items through AI signal extraction
  5. Generates intelligence alerts for high-confidence signals
  6. Triggers forecast re-run on regime-change signals
"""

from __future__ import annotations

import json
import os
import sys
from dataclasses import asdict, dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

# Ensure project root on path
project_root = str(Path(__file__).resolve().parent.parent.parent)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from forecasting.scrapers.ipart_scraper import scrape_ipart_news
from forecasting.scrapers.ecovantage_scraper import scrape_ecovantage
from forecasting.scrapers.northmore_scraper import scrape_northmore_gordon

DB_URL = os.environ.get("POSTGRES_URL") or os.environ.get("DATABASE_URL")

# ---------------------------------------------------------------------------
# Alert data type
# ---------------------------------------------------------------------------

@dataclass
class IntelligenceAlert:
    """An intelligence alert generated by the monitoring system."""
    alert_type: str          # policy | creation_anomaly | sentiment | surplus | regime | system
    severity: str            # info | warning | critical
    title: str
    summary: str
    estimated_price_impact_pct: float
    source: str
    source_url: str
    metadata: Dict[str, Any]
    created_at: str
    acknowledged_at: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Database helpers
# ---------------------------------------------------------------------------

def _get_db_connection():
    if not DB_URL:
        return None
    try:
        import psycopg2
        return psycopg2.connect(DB_URL)
    except Exception as e:
        print(f"[monitor] DB connection failed: {e}", file=sys.stderr)
        return None


def _get_last_scrape_date(conn, source: str) -> Optional[str]:
    """Get the most recent scrape date for a given source."""
    if not conn:
        return None
    try:
        cur = conn.cursor()
        cur.execute(
            "SELECT MAX(created_at::date) FROM intelligence_alerts WHERE source = %s",
            (source,),
        )
        row = cur.fetchone()
        cur.close()
        return str(row[0]) if row and row[0] else None
    except Exception:
        return None


def store_alert(conn, alert: IntelligenceAlert) -> Optional[int]:
    """Store an alert in the intelligence_alerts table. Returns alert ID."""
    if not conn:
        return None
    try:
        cur = conn.cursor()
        cur.execute(
            """INSERT INTO intelligence_alerts
                (alert_type, severity, title, summary,
                 estimated_price_impact_pct, source, source_url,
                 metadata, created_at, acknowledged_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id""",
            (
                alert.alert_type, alert.severity, alert.title, alert.summary,
                alert.estimated_price_impact_pct, alert.source, alert.source_url,
                json.dumps(alert.metadata), alert.created_at, alert.acknowledged_at,
            ),
        )
        alert_id = cur.fetchone()[0]
        conn.commit()
        cur.close()
        return alert_id
    except Exception as e:
        print(f"[monitor] store_alert error: {e}", file=sys.stderr)
        try:
            conn.rollback()
        except Exception:
            pass
        return None


# ---------------------------------------------------------------------------
# Source monitors
# ---------------------------------------------------------------------------

def check_ipart(conn) -> List[IntelligenceAlert]:
    """Check for new IPART publications and extract signals."""
    alerts: List[IntelligenceAlert] = []
    print("  [monitor] Checking IPART...")

    try:
        items = scrape_ipart_news()
        if not items:
            return alerts

        last_date = _get_last_scrape_date(conn, "ipart")

        for item in items:
            item_date = item.get("date")
            # Skip items we've already processed
            if last_date and item_date and item_date <= last_date:
                continue

            # Try AI signal extraction if API key is available
            signal = _try_extract_policy_signal(item)
            if signal and signal.get("confidence", 0) > 0.6:
                impact = abs(signal.get("supply_impact_magnitude_pct", 0))
                if impact > 2:
                    severity = "critical" if impact > 10 else "warning"
                    alerts.append(IntelligenceAlert(
                        alert_type="policy",
                        severity=severity,
                        title=f"IPART: {item.get('title', 'New publication')[:120]}",
                        summary=signal.get("summary", item.get("summary", "")),
                        estimated_price_impact_pct=signal.get("supply_impact_magnitude_pct", 0),
                        source="ipart",
                        source_url=item.get("url", ""),
                        metadata={
                            "affected_activities": signal.get("affected_activities", []),
                            "supply_impact": signal.get("supply_impact_direction"),
                            "demand_impact": signal.get("demand_impact_direction"),
                            "implementation_date": signal.get("implementation_date"),
                            "confidence": signal.get("confidence"),
                        },
                        created_at=datetime.utcnow().isoformat(),
                    ))
    except Exception as e:
        print(f"  [monitor] IPART check error: {e}", file=sys.stderr)

    return alerts


def check_broker_updates(conn) -> List[IntelligenceAlert]:
    """Check Ecovantage and NMG for new market updates."""
    alerts: List[IntelligenceAlert] = []
    print("  [monitor] Checking broker updates...")

    sources = [
        ("ecovantage", scrape_ecovantage),
        ("northmore_gordon", scrape_northmore_gordon),
    ]

    for source_name, scraper in sources:
        try:
            data = scraper()
            if not data:
                continue

            # Try AI sentiment extraction
            sentiment = _try_extract_broker_sentiment(data, source_name)
            if not sentiment:
                continue

            concern = sentiment.get("supply_concern_level", 5)
            direction = sentiment.get("price_direction", "flat")

            # Alert if sentiment is extreme
            if concern >= 7 or concern <= 2:
                severity = "warning" if concern >= 7 else "info"
                direction_text = {"up": "bullish", "down": "bearish"}.get(direction, "neutral")
                alerts.append(IntelligenceAlert(
                    alert_type="sentiment",
                    severity=severity,
                    title=f"{source_name.title()}: {direction_text} sentiment (concern={concern:.0f}/10)",
                    summary=f"Key themes: {', '.join(sentiment.get('key_themes', []))}",
                    estimated_price_impact_pct=_sentiment_to_impact(direction, concern),
                    source=source_name,
                    source_url="",
                    metadata=sentiment,
                    created_at=datetime.utcnow().isoformat(),
                ))
        except Exception as e:
            print(f"  [monitor] {source_name} check error: {e}", file=sys.stderr)

    return alerts


def check_dcceew(conn) -> List[IntelligenceAlert]:
    """Check for NSW DCCEEW publications (energy.nsw.gov.au)."""
    alerts: List[IntelligenceAlert] = []
    print("  [monitor] Checking DCCEEW...")

    try:
        import requests
        resp = requests.get(
            "https://www.energy.nsw.gov.au/nsw-plans-and-progress/regulation-and-policy/energy-security-safeguard",
            headers={"User-Agent": "WREI-Platform/1.0 (market-data-feed)"},
            timeout=20,
        )
        if resp.status_code != 200:
            return alerts

        from bs4 import BeautifulSoup
        soup = BeautifulSoup(resp.text, "html.parser")

        # Look for recent news/updates sections
        for link in soup.find_all("a", href=True):
            text = link.get_text(strip=True)
            href = link.get("href", "")
            if len(text) < 15:
                continue
            # Filter for ESS-relevant content
            import re
            if not re.search(r"(?:energy.sav|ESS|certific|safeguard|target)", text, re.IGNORECASE):
                continue

            full_url = href if href.startswith("http") else f"https://www.energy.nsw.gov.au{href}"

            signal = _try_extract_legislative_signal(text, "dcceew")
            if signal and signal.get("confidence", 0) > 0.6:
                total_impact = abs(signal.get("supply_impact_pct", 0)) + abs(signal.get("demand_impact_pct", 0))
                if total_impact > 2:
                    alerts.append(IntelligenceAlert(
                        alert_type="policy",
                        severity="warning" if total_impact > 5 else "info",
                        title=f"DCCEEW: {text[:120]}",
                        summary=signal.get("change_description", ""),
                        estimated_price_impact_pct=signal.get("supply_impact_pct", 0),
                        source="dcceew",
                        source_url=full_url,
                        metadata=signal,
                        created_at=datetime.utcnow().isoformat(),
                    ))
                    break  # One alert per scan is sufficient

    except Exception as e:
        print(f"  [monitor] DCCEEW check error: {e}", file=sys.stderr)

    return alerts


# ---------------------------------------------------------------------------
# AI extraction wrappers (graceful degradation without API key)
# ---------------------------------------------------------------------------

def _try_extract_policy_signal(item: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """Try to extract a policy signal. Returns None if API unavailable."""
    if not os.environ.get("ANTHROPIC_API_KEY"):
        # Return a basic signal from metadata alone
        return {
            "confidence": 0.4,
            "summary": item.get("summary", item.get("title", "")),
            "supply_impact_magnitude_pct": 0,
            "supply_impact_direction": "neutral",
            "demand_impact_direction": "neutral",
            "affected_activities": [],
        }
    try:
        from forecasting.signals.ai_signal_extractor import extract_policy_signal
        text = item.get("summary", "") or item.get("title", "")
        signal = extract_policy_signal(
            document_text=text,
            document_type="publication",
            publication_date=item.get("date", date.today().isoformat()),
        )
        return asdict(signal)
    except Exception as e:
        print(f"  [monitor] Signal extraction failed: {e}", file=sys.stderr)
        return None


def _try_extract_broker_sentiment(data: Dict[str, Any], source: str) -> Optional[Dict[str, Any]]:
    """Try to extract broker sentiment. Returns None if API unavailable."""
    if not os.environ.get("ANTHROPIC_API_KEY"):
        return None
    try:
        from forecasting.signals.ai_signal_extractor import extract_broker_sentiment
        text = json.dumps(data)
        sentiment = extract_broker_sentiment(
            commentary_text=text,
            source=source,
            publication_date=date.today().isoformat(),
        )
        return asdict(sentiment)
    except Exception:
        return None


def _try_extract_legislative_signal(text: str, source: str) -> Optional[Dict[str, Any]]:
    """Try to extract a legislative signal. Returns None if API unavailable."""
    if not os.environ.get("ANTHROPIC_API_KEY"):
        return None
    try:
        from forecasting.signals.ai_signal_extractor import extract_legislative_signal
        signal = extract_legislative_signal(text=text, source=source)
        return asdict(signal)
    except Exception:
        return None


def _sentiment_to_impact(direction: str, concern: float) -> float:
    """Convert sentiment direction + concern level to estimated price impact %."""
    base = {"up": 3.0, "down": -3.0, "flat": 0.0}.get(direction, 0.0)
    # Scale by deviation from neutral (5)
    scale = (concern - 5) / 5.0  # -1 to +1
    return round(base + scale * 2.0, 2)


# ---------------------------------------------------------------------------
# Regime change detection
# ---------------------------------------------------------------------------

def check_regime_change(alerts: List[IntelligenceAlert]) -> bool:
    """
    Check if any alert implies a regime change requiring forecast re-run.
    Regime change = supply_impact > 10% or demand_impact > 5%.
    """
    for alert in alerts:
        meta = alert.metadata
        supply = abs(meta.get("supply_impact_magnitude_pct", 0) or
                     meta.get("supply_impact_pct", 0) or 0)
        demand = abs(meta.get("demand_impact_pct", 0) or 0)

        if supply > 10 or demand > 5:
            print(f"  [monitor] REGIME CHANGE detected: supply={supply}%, demand={demand}%")
            return True

    return False


# ---------------------------------------------------------------------------
# Main monitor function
# ---------------------------------------------------------------------------

def run_monitor() -> Dict[str, Any]:
    """
    Run the full monitoring sweep.

    Returns dict with alerts generated, regime change flag, and status.
    """
    print("[monitor] Starting continuous monitoring sweep...")
    conn = _get_db_connection()

    all_alerts: List[IntelligenceAlert] = []

    # 1. Check all sources
    all_alerts.extend(check_ipart(conn))
    all_alerts.extend(check_broker_updates(conn))
    all_alerts.extend(check_dcceew(conn))

    # 2. Store alerts
    stored_ids = []
    for alert in all_alerts:
        alert_id = store_alert(conn, alert)
        if alert_id:
            stored_ids.append(alert_id)

    # 3. Check for regime change
    regime_change = check_regime_change(all_alerts)

    # 4. Trigger forecast re-run if regime change detected
    if regime_change:
        print("  [monitor] Triggering forecast re-run due to regime change...")
        try:
            from forecasting.generate_forecast import generate
            generate(csv_only=not bool(DB_URL))
            print("  [monitor] Forecast re-run complete.")
        except Exception as e:
            print(f"  [monitor] Forecast re-run failed: {e}", file=sys.stderr)

    if conn:
        conn.close()

    result = {
        "timestamp": datetime.utcnow().isoformat(),
        "alerts_generated": len(all_alerts),
        "alerts_stored": len(stored_ids),
        "regime_change_detected": regime_change,
        "alerts": [a.to_dict() for a in all_alerts],
    }

    print(f"[monitor] Sweep complete: {len(all_alerts)} alerts generated, "
          f"regime_change={regime_change}")

    return result


if __name__ == "__main__":
    result = run_monitor()
    print(json.dumps(result, indent=2, default=str))
